server:
  port: 8000

spring:
  application:
    name: gateway

  cloud:
    gateway:
      routes:
        - id: product-service
          uri: http://localhost:8081
          predicates:
            - Path=/
            - Path=/categories/**
            - Path=/categories
            - Path=/product/{id_item}
            - Path=/search
            - Path=/privacy
            - Path=/about
            - Path=/terms
            - Path=/contacts
            - Path=/send-message

    loadbalancer:
      ribbon:
        enabled: false

eureka:
  instance:
    prefer-ip-address: true
    hostname: api-gateway
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true
