package Department_HomeAppliances

import (
	"context"
	"parseAndSendData_service/RetrieveDataFromDepartments/Department_HomeAppliances/Category_ClimateControl"
	"parseAndSendData_service/RetrieveDataFromDepartments/Department_HomeAppliances/Category_HomeAppliances"
	"parseAndSendData_service/RetrieveDataFromDepartments/Department_HomeAppliances/Category_KitchenAppliances"
)

func GetDataFromDepartmentHomeAppliances(ctx context.Context) {
	//Category_ClimateControl
	Category_ClimateControl.GetDataCategoryAirConditioners(ctx)
	Category_ClimateControl.GetDataCategoryHeaters(ctx)
	Category_ClimateControl.GetDataCategoryFans(ctx)
	Category_ClimateControl.GetDataCategoryHumidifiersAndAirPurifiers(ctx)

	//Category_HomeAppliances
	Category_HomeAppliances.GetDataCategoryVacuumCleaners(ctx)
	Category_HomeAppliances.GetDataCategoryVacuumCleanerAccessories(ctx)
	Category_HomeAppliances.GetDataCategoryWashingMachines(ctx)
	Category_HomeAppliances.GetDataCategoryWaterHeaters(ctx)
	Category_HomeAppliances.GetDataCategoryFaucetWaterHeaters(ctx)
	Category_HomeAppliances.GetDataCategoryIronsSteamers(ctx)
	Category_HomeAppliances.GetDataCategoryClothingCare(ctx)
	Category_HomeAppliances.GetDataCategoryHomeCleaning(ctx)
	Category_HomeAppliances.GetDataCategorySteamCleaners(ctx)
	Category_HomeAppliances.GetDataCategoryWindowCleaners(ctx)
	Category_HomeAppliances.GetDataCategoryPhones(ctx)
	Category_HomeAppliances.GetDataCategoryStabilizers(ctx)

	//Category_KitchenAppliances
	Category_KitchenAppliances.GetDataCategoryRefrigerators(ctx)
	Category_KitchenAppliances.GetDataCategoryFreezers(ctx)
	Category_KitchenAppliances.GetDataCategoryIceMakers(ctx)
	Category_KitchenAppliances.GetDataCategoryWineCoolers(ctx)
	Category_KitchenAppliances.GetDataCategoryMicrowaves(ctx)
	Category_KitchenAppliances.GetDataCategoryCooktops(ctx)
	Category_KitchenAppliances.GetDataCategoryOvens(ctx)
	Category_KitchenAppliances.GetDataCategoryElectricOvens(ctx)
	Category_KitchenAppliances.GetDataCategoryStoves(ctx)
	Category_KitchenAppliances.GetDataCategoryInductionCookers(ctx)
	Category_KitchenAppliances.GetDataCategoryRangeHoods(ctx)
	Category_KitchenAppliances.GetDataCategoryKettles(ctx)
	Category_KitchenAppliances.GetDataCategoryBlendersJuicers(ctx)
	Category_KitchenAppliances.GetDataCategoryMixers(ctx)
	Category_KitchenAppliances.GetDataCategoryFoodProcessors(ctx)
	Category_KitchenAppliances.GetDataCategoryMultiCookers(ctx)
	Category_KitchenAppliances.GetDataCategoryIceCreamMakers(ctx)
	Category_KitchenAppliances.GetDataCategoryFoodDehydrators(ctx)
	Category_KitchenAppliances.GetDataCategoryYogurtMakers(ctx)
	Category_KitchenAppliances.GetDataCategoryBreadMakers(ctx)
	Category_KitchenAppliances.GetDataCategoryCoffeeMachines(ctx)
	Category_KitchenAppliances.GetDataCategoryCoffeeGrinders(ctx)
	Category_KitchenAppliances.GetDataCategoryTurkishCoffeePots(ctx)
	Category_KitchenAppliances.GetDataCategoryKitchenScales(ctx)
	Category_KitchenAppliances.GetDataCategoryToastersGrills(ctx)
	Category_KitchenAppliances.GetDataCategoryVacuumSealers(ctx)
	Category_KitchenAppliances.GetDataCategoryWaffleMakers(ctx)
	Category_KitchenAppliances.GetDataCategoryDeepFryers(ctx)
	Category_KitchenAppliances.GetDataCategorySandwichMakers(ctx)
	Category_KitchenAppliances.GetDataCategoryMeatGrinders(ctx)
	Category_KitchenAppliances.GetDataCategoryElectricGrills(ctx)
	Category_KitchenAppliances.GetDataCategoryKitchenGadgets(ctx)
}
