server:
  port: 8080

spring:
  application:
    name: gateway

  cloud:
    gateway:
      routes:
        - id: PRODUCT_SERVICE
          uri: lb://PRODUCT_SERVICE
          predicates:
            - Path=/
            - Path=/categories/**
            - Path=/product/{id_item}
            - Path=/search
            - Path=/privacy
            - Path=/about
            - Path=/terms
            - Path=/contacts
            - Path=/send-message
          filters:
            - StripPrefix=1
        - id: GOLANG_PARSER_SERVICE
          uri: lb://GOLANG_PARSER_SERVICE
          predicates:
            - Path=/go_client/**
          filters:
            - StripPrefix=1
        - id: default_route
          uri: lb://PRODUCT_SERVICE
          predicates:
            - Path=/**
          filters:
            - StripPrefix=1

  eureka:
    client:
      serviceUrl:
        defaultZone: http://eureka-server:8761/eureka/
      registerWithEureka: true
      fetchRegistry: true

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.web: TRACE

management:
  endpoints:
    web:
      exposure:
        include: self, gateway, beans, health
    enabled-by-default: true
    gateway:
      enabled: true
  endpoint:
    health:
      show-details: always
