package Department_OfficeEquipmentAndSupplies

import (
	"context"
	"parseAndSendData_service/RetrieveDataFromDepartments/Department_OfficeEquipmentAndSupplies/Category_ConsumablesAndAccessories"
	"parseAndSendData_service/RetrieveDataFromDepartments/Department_OfficeEquipmentAndSupplies/Category_DemonstrationEquipment"
	"parseAndSendData_service/RetrieveDataFromDepartments/Department_OfficeEquipmentAndSupplies/Category_OfficeAndCommercialEquipment"
	"parseAndSendData_service/RetrieveDataFromDepartments/Department_OfficeEquipmentAndSupplies/Category_PrintingDevices"
)

func GetDataFromDepartment_OfficeEquipmentAndSupplies(ctx context.Context) {
	//Category_ConsumablesAndAccessories
	Category_ConsumablesAndAccessories.GetDataCategoryPaperAndPhotoPaper(ctx)
	Category_ConsumablesAndAccessories.GetDataCategoryLaserCartridges(ctx)
	Category_ConsumablesAndAccessories.GetDataCategoryInkCartridgesAndInks(ctx)
	Category_ConsumablesAndAccessories.GetDataCategoryTonersForLaserPrinters(ctx)
	Category_ConsumablesAndAccessories.GetDataCategoryConsumablesForLaserPrinters(ctx)
	Category_ConsumablesAndAccessories.GetDataCategoryDotMatrixCartridges(ctx)
	Category_ConsumablesAndAccessories.GetDataCategoryConsumablesForCopiers(ctx)
	Category_ConsumablesAndAccessories.GetDataCategoryFilmsForLaminators(ctx)
	Category_ConsumablesAndAccessories.GetDataCategoryAccessoriesForBindingMachines(ctx)
	Category_ConsumablesAndAccessories.GetDataCategoryPlasticFor3DPrinting(ctx)
	Category_ConsumablesAndAccessories.GetDataCategoryCablesAndAdapters(ctx)
	Category_ConsumablesAndAccessories.GetDataCategoryCleaningProducts(ctx)

	//Category_DemonstrationEquipment
	Category_DemonstrationEquipment.GetDataCategoryProjectors(ctx)
	Category_DemonstrationEquipment.GetDataCategoryProjectionScreens(ctx)
	Category_DemonstrationEquipment.GetDataCategoryInteractivePanels(ctx)
	Category_DemonstrationEquipment.GetDataCategoryProjectorMounts(ctx)
	Category_DemonstrationEquipment.GetDataCategoryWhiteboardsAndAccessories(ctx)

	//Category_OfficeAndCommercialEquipment
	Category_OfficeAndCommercialEquipment.GetDataCategoryTelephones(ctx)
	Category_OfficeAndCommercialEquipment.GetDataCategoryCutters(ctx)
	Category_OfficeAndCommercialEquipment.GetDataCategoryLaminators(ctx)
	Category_OfficeAndCommercialEquipment.GetDataCategoryShredders(ctx)
	Category_OfficeAndCommercialEquipment.GetDataCategoryBindingMachines(ctx)
	Category_OfficeAndCommercialEquipment.GetDataCategoryTradeEquipment(ctx)

	//Category_Computers
	Category_PrintingDevices.GetDataCategoryLaserMFPs(ctx)
	Category_PrintingDevices.GetDataCategoryLaserPrinters(ctx)
	Category_PrintingDevices.GetDataCategoryInkjetPrinters(ctx)
	Category_PrintingDevices.GetDataCategoryCopiers(ctx)
	Category_PrintingDevices.GetDataCategoryPlotters(ctx)
	Category_PrintingDevices.GetDataCategory3DPrinters(ctx)
	Category_PrintingDevices.GetDataCategory3DPens(ctx)
}
