package Department_Accessories

import (
	"context"
	"parseAndSendData_service/RetrieveDataFromDepartments/Department_Accessories/Category_EverythingForBuilding_a_Computer"
	"parseAndSendData_service/RetrieveDataFromDepartments/Department_Accessories/Category_Furniture"
	"parseAndSendData_service/RetrieveDataFromDepartments/Department_Accessories/Category_Periphery"
)

func GetDataFromDepartmentAccessories(ctx context.Context) {
	//Category_EverythingForBuilding_a_Computer
	Category_EverythingForBuilding_a_Computer.GetDataCategoryCPU(ctx)
	Category_EverythingForBuilding_a_Computer.GetDataCategoryMotherboards(ctx)
	Category_EverythingForBuilding_a_Computer.GetDataCategoryRAM(ctx)
	Category_EverythingForBuilding_a_Computer.GetDataCategoryGPU(ctx)
	Category_EverythingForBuilding_a_Computer.GetDataCategoryHardDrives(ctx)
	Category_EverythingForBuilding_a_Computer.GetDataCategorySDDrives(ctx)
	Category_EverythingForBuilding_a_Computer.GetDataCategoryPowerSupplyUnits(ctx)
	Category_EverythingForBuilding_a_Computer.GetDataCategoryEnclosures(ctx)
	Category_EverythingForBuilding_a_Computer.GetDataCategoryCPUCoolers(ctx)
	Category_EverythingForBuilding_a_Computer.GetDataCategoryWaterCoolingSystems(ctx)
	Category_EverythingForBuilding_a_Computer.GetDataCategoryThermalPaste(ctx)
	Category_EverythingForBuilding_a_Computer.GetDataCategoryDrives(ctx)

	//Category_Furniture
	Category_Furniture.GetDataCategoryGamingChairs(ctx)
	Category_Furniture.GetDataCategoryTablesForGamers(ctx)

	//Category_Periphery
	Category_Periphery.GetDataCategoryGamingMice(ctx)
	Category_Periphery.GetDataCategoryGamingMousePads(ctx)
	Category_Periphery.GetDataCategoryGamingKeyboards(ctx)
	Category_Periphery.GetDataCategoryGamingHeadphones(ctx)
	Category_Periphery.GetDataCategoryJoysticksHandlebarsGamepads(ctx)
	Category_Periphery.GetDataCategoryControllersForStreaming(ctx)
	Category_Periphery.GetDataCategoryGamingMonitors(ctx)
}
