package irmag.io.ProductService.Entity;

import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class KeywordCategoryMap {

    public static Map<String, List<String>> getKeywordMap() {
        Map<String, List<String>> keywordCategoryMap = new HashMap<>();
        keywordCategoryMap.put("телефоны", Arrays.asList("Смартфоны", "Мобильные телефоны"));
        keywordCategoryMap.put("телефон", Arrays.asList("Смартфоны", "Мобильные телефоны"));
        keywordCategoryMap.put("phone", Arrays.asList("Смартфоны", "Мобильные телефоны"));
        keywordCategoryMap.put("phones", Arrays.asList("Смартфоны", "Мобильные телефоны"));
        keywordCategoryMap.put("смартфон", Arrays.asList("Смартфоны", "Мобильные телефоны"));
        keywordCategoryMap.put("смартфоны", Arrays.asList("Смартфоны", "Мобильные телефоны"));
        keywordCategoryMap.put("smartphone", Arrays.asList("Смартфоны", "Мобильные телефоны"));
        keywordCategoryMap.put("smartphones", Arrays.asList("Смартфоны", "Мобильные телефоны"));
        keywordCategoryMap.put("компьютер", Arrays.asList("ПК", "Моноблоки", "Настольные компьютеры"));
        keywordCategoryMap.put("компьютеры", Arrays.asList("ПК", "Моноблоки", "Настольные компьютеры"));
        keywordCategoryMap.put("pc", Arrays.asList("ПК", "Моноблоки", "Настольные компьютеры"));
        keywordCategoryMap.put("ноутбук", List.of("Ноутбуки"));
        keywordCategoryMap.put("ноутбуки", List.of("Ноутбуки"));
        keywordCategoryMap.put("сотовые телефоны", Arrays.asList("Смартфоны", "Мобильные телефоны"));
        keywordCategoryMap.put("кнопочные телефоны", List.of("Мобильные телефоны"));
        keywordCategoryMap.put("гаджеты", Arrays.asList("Смарт-часы", "Фитнес-браслеты", "Планшеты", "Электронные книги", "Аксессуары"));
        keywordCategoryMap.put("планшет", List.of("Планшеты"));
        keywordCategoryMap.put("планшеты", List.of("Планшеты"));
        keywordCategoryMap.put("фитнес браслет", List.of("Фитнес-браслеты"));
        keywordCategoryMap.put("фитнес браслеты", List.of("Фитнес-браслеты"));
        keywordCategoryMap.put("повербанк", List.of("Power bank (мобильные аккумуляторы)"));
        keywordCategoryMap.put("павербанк", List.of("Power bank (мобильные аккумуляторы)"));
        keywordCategoryMap.put("power bank", List.of("Power bank (мобильные аккумуляторы)"));
        keywordCategoryMap.put("наушники", Arrays.asList("Наушники для телефонов", "Беспроводные наушники и гарнитуры"));
        keywordCategoryMap.put("беспроводные наушники", List.of("Беспроводные наушники и гарнитуры"));
        keywordCategoryMap.put("чехол для смартфона", List.of("Чехлы для смартфонов"));
        keywordCategoryMap.put("чехол для наушников", List.of("Чехлы для наушников"));
        keywordCategoryMap.put("видеокарты", List.of("Видеокарты"));
        keywordCategoryMap.put("ссд", List.of("SSD диски"));
        keywordCategoryMap.put("ссд диски", List.of("SSD диски"));
        keywordCategoryMap.put("ssd", List.of("SSD диски"));
        keywordCategoryMap.put("ssd диски", List.of("SSD диски"));
        keywordCategoryMap.put("моноблок", List.of("Моноблоки"));
        keywordCategoryMap.put("монитор", List.of("Мониторы"));
        keywordCategoryMap.put("мышь", List.of("Мыши"));
        keywordCategoryMap.put("клавиатура", List.of("Клавиатуры"));
        keywordCategoryMap.put("акустика", List.of("Акустические системы и колонки"));
        keywordCategoryMap.put("графический планшет", List.of("Графические планшеты"));
        keywordCategoryMap.put("usb hub", List.of("USB-hub"));
        keywordCategoryMap.put("принтер", Arrays.asList("Принтеры струйные", "Принтеры лазерные"));
        keywordCategoryMap.put("сканер", List.of("Сканеры"));
        keywordCategoryMap.put("3d принтер", List.of("3D принтеры"));
        keywordCategoryMap.put("фотоаппарат", List.of("Фотоаппараты"));
        keywordCategoryMap.put("блендер", List.of("Блендеры, соковыжималки"));
        keywordCategoryMap.put("кофеварка", List.of("Кофеварки, кофемашины"));
        keywordCategoryMap.put("миксер", List.of("Миксеры"));
        keywordCategoryMap.put("пылесос", List.of("Пылесосы"));
        keywordCategoryMap.put("весы", List.of("Весы кухонные"));
        keywordCategoryMap.put("уборка", List.of("Уборка дома"));
        keywordCategoryMap.put("инструмент", List.of("Инструменты и электроинструменты"));
        keywordCategoryMap.put("игровой ноутбук", List.of("Игровые ноутбуки"));
        keywordCategoryMap.put("игровой компьютер", List.of("Игровые компьютеры"));
        keywordCategoryMap.put("игровой кресло", List.of("Игровые кресла"));
        keywordCategoryMap.put("пульт", List.of("Пульты"));
        keywordCategoryMap.put("телевизор", List.of("Телевизоры"));
        keywordCategoryMap.put("аудиотехника", List.of("Аудиотехника, Hi-Fi оборудование"));
        keywordCategoryMap.put("фототехника", Arrays.asList("Фотоаппараты", "Аксессуары для фотоаппаратов"));
        keywordCategoryMap.put("бытовая техника", List.of("Бытовая техника"));
        keywordCategoryMap.put("стирка", List.of("Уход за одеждой"));
        keywordCategoryMap.put("массажер", List.of("Массажеры"));
        keywordCategoryMap.put("бытовая химия", List.of("Бытовая химия"));
        keywordCategoryMap.put("умный дом", List.of("Умный дом"));
        keywordCategoryMap.put("канцтовары", List.of("Канцтовары"));
        keywordCategoryMap.put("apple", Arrays.asList("Apple", "iPhone"));
        keywordCategoryMap.put("эпл", Arrays.asList("Apple", "iPhone"));
        keywordCategoryMap.put("iphone", List.of("iPhone"));
        keywordCategoryMap.put("айфон", List.of("iPhone"));
        keywordCategoryMap.put("ипхон", List.of("iPhone"));
        keywordCategoryMap.put("samsung", Arrays.asList("Samsung", "Galaxy"));
        keywordCategoryMap.put("самсунг", Arrays.asList("Samsung", "Galaxy"));
        keywordCategoryMap.put("самсунг телефон", List.of("Galaxy"));
        keywordCategoryMap.put("гелекси", Arrays.asList("Samsung", "Galaxy"));
        keywordCategoryMap.put("galaxy", Arrays.asList("Samsung", "Galaxy"));
        keywordCategoryMap.put("huawei", List.of("Huawei"));
        keywordCategoryMap.put("хуавей", List.of("Huawei"));
        keywordCategoryMap.put("honor", List.of("Honor"));
        keywordCategoryMap.put("хонор", List.of("Honor"));
        keywordCategoryMap.put("xiaomi", List.of("Xiaomi"));
        keywordCategoryMap.put("ксиоми", List.of("Xiaomi"));
        keywordCategoryMap.put("ксиаоми", List.of("Xiaomi"));
        keywordCategoryMap.put("redmi", List.of("Redmi"));
        keywordCategoryMap.put("редми", List.of("Redmi"));
        keywordCategoryMap.put("oppo", List.of("Oppo"));
        keywordCategoryMap.put("оппо", List.of("Oppo"));
        keywordCategoryMap.put("realme", List.of("Realme"));
        keywordCategoryMap.put("реалми", List.of("Realme"));
        keywordCategoryMap.put("oneplus", List.of("OnePlus"));
        keywordCategoryMap.put("онеплас", List.of("OnePlus"));
        keywordCategoryMap.put("уанплюс", List.of("OnePlus"));
        keywordCategoryMap.put("nokia", List.of("Nokia"));
        keywordCategoryMap.put("нокиа", List.of("Nokia"));
        keywordCategoryMap.put("acer", List.of("Acer"));
        keywordCategoryMap.put("асер", List.of("Acer"));
        keywordCategoryMap.put("asus", List.of("Asus"));
        keywordCategoryMap.put("асус", List.of("Asus"));
        keywordCategoryMap.put("эйсус", List.of("Asus"));
        keywordCategoryMap.put("lenovo", List.of("Lenovo"));
        keywordCategoryMap.put("леново", List.of("Lenovo"));
        keywordCategoryMap.put("msi", List.of("MSI"));
        keywordCategoryMap.put("мси", List.of("MSI"));
        keywordCategoryMap.put("эмэсай", List.of("MSI"));
        keywordCategoryMap.put("dell", List.of("Dell"));
        keywordCategoryMap.put("дэлл", List.of("Dell"));
        keywordCategoryMap.put("hp", List.of("HP"));
        keywordCategoryMap.put("хп", List.of("HP"));
        keywordCategoryMap.put("эйчпи", List.of("HP"));
        keywordCategoryMap.put("corsair", List.of("Corsair"));
        keywordCategoryMap.put("корсар", List.of("Corsair"));
        keywordCategoryMap.put("kingston", List.of("Kingston"));
        keywordCategoryMap.put("кингстон", List.of("Kingston"));
        keywordCategoryMap.put("samsung", List.of("Samsung"));
        keywordCategoryMap.put("самсунг", List.of("Samsung"));
        keywordCategoryMap.put("seagate", List.of("Seagate"));
        keywordCategoryMap.put("сигейт", List.of("Seagate"));
        keywordCategoryMap.put("western digital", List.of("Western Digital"));
        keywordCategoryMap.put("вестерн диджитал", List.of("Western Digital"));
        keywordCategoryMap.put("amd", List.of("AMD"));
        keywordCategoryMap.put("амд", List.of("AMD"));
        keywordCategoryMap.put("эмд", List.of("AMD"));
        keywordCategoryMap.put("intel", List.of("Intel"));
        keywordCategoryMap.put("интел", List.of("Intel"));
        return keywordCategoryMap;
    }
}
