package Department_EntertainmentAndRecreation

import (
	"context"
	"parseAndSendData_service/RetrieveDataFromDepartments/Department_EntertainmentAndRecreation/Category_Entertainment"
	"parseAndSendData_service/RetrieveDataFromDepartments/Department_EntertainmentAndRecreation/Category_Toys"
	"parseAndSendData_service/RetrieveDataFromDepartments/Department_EntertainmentAndRecreation/Category_Transport"
	"parseAndSendData_service/RetrieveDataFromDepartments/Department_EntertainmentAndRecreation/Category_TravelLeisure"
)

func GetDataFromDepartment_EntertainmentAndRecreation(ctx context.Context) {
	//Category_Entertainment
	Category_Entertainment.GetDataCategoryBinoculars(ctx)
	Category_Entertainment.GetDataCategoryEBooks(ctx)

	//Category_Toys
	Category_Toys.GetDataCategoryRCToys(ctx)
	Category_Toys.GetDataCategoryToyCars(ctx)
	Category_Toys.GetDataCategoryConstructors(ctx)
	Category_Toys.GetDataCategoryLEGO(ctx)
	Category_Toys.GetDataCategoryEducationalToys(ctx)
	Category_Toys.GetDataCategory3DPens(ctx)

	//Category_Transport
	Category_Transport.GetDataCategoryHoverboards(ctx)
	Category_Transport.GetDataCategorySegways(ctx)
	Category_Transport.GetDataCategoryElectricScootersBikes(ctx)

	//Category_TravelLeisure
	Category_TravelLeisure.GetDataCategorySuitcases(ctx)
	Category_TravelLeisure.GetDataCategoryBagsBackpacks(ctx)
	Category_TravelLeisure.GetDataCategoryTourism(ctx)
	Category_TravelLeisure.GetDataCategoryAirMattresses(ctx)
	Category_TravelLeisure.GetDataCategoryBeachHoliday(ctx)
	Category_TravelLeisure.GetDataCategoryPools(ctx)
	Category_TravelLeisure.GetDataCategoryPoolAccessories(ctx)
	Category_TravelLeisure.GetDataCategoryTrampolines(ctx)
	Category_TravelLeisure.GetDataCategoryInflatableBoats(ctx)
}
