package Department_ComputerPeripherals

import (
	"context"
	"parseAndSendData_service/RetrieveDataFromDepartments/Department_ComputerPeripherals/Category_Media"
	"parseAndSendData_service/RetrieveDataFromDepartments/Department_ComputerPeripherals/Category_Periphery"
)

func GetDataFromDepartment_ComputerPeripherals(ctx context.Context) {
	//Category_Media
	Category_Media.GetDataCategoryFlashDrives(ctx)
	Category_Media.GetDataCategoryMemoryCards(ctx)
	Category_Media.GetDataCategoryUSB(ctx)
	Category_Media.GetDataCategoryNetworkStorage(ctx)

	//Category_Periphery
	Category_Periphery.GetDataCategoryMonitors(ctx)
	Category_Periphery.GetDataCategoryMonitorMounts(ctx)
	Category_Periphery.GetDataCategoryMouses(ctx)
	Category_Periphery.GetDataCategoryMousePads(ctx)
	Category_Periphery.GetDataCategoryKeyboards(ctx)
	Category_Periphery.GetDataCategoryKeyboardAccessories(ctx)
	Category_Periphery.GetDataCategoryStickersForKeyboards(ctx)
	Category_Periphery.GetDataCategoryAcousticSystemsAndSpeakers(ctx)
	Category_Periphery.GetDataCategoryHeadphonesAndHeadsets(ctx)
	Category_Periphery.GetDataCategoryMicrophones(ctx)
	Category_Periphery.GetDataCategoryWebcams(ctx)
	Category_Periphery.GetDataCategoryUPS(ctx)
	Category_Periphery.GetDataCategoryBatteriesForUPS(ctx)
	Category_Periphery.GetDataCategoryStabilizers(ctx)
	Category_Periphery.GetDataCategoryNetworkFiltersAdapters(ctx)
	Category_Periphery.GetDataCategoryJoysticksHandlebarsGamepads(ctx)
	Category_Periphery.GetDataCategoryControllersForStreaming(ctx)
	Category_Periphery.GetDataCategoryGraphicTablets(ctx)
	Category_Periphery.GetDataCategoryUSBHub(ctx)
	Category_Periphery.GetDataCategoryCardReaders(ctx)
}
